### ISSUE TITLE
[typo] v1.3?

### ISSUE THREAD

**Issue by goofy7264** [damvcoool/Marlin-2.0.x-SKR-Mini-E3-v1.2#1]
Is it a typo in the readme.md for SKR Mini E3 v1.3?  Should this be version 1.2?

**Comment by damvcoool** [comment]
Thank you!
I have corrected it.
I hope you find my notes useful :)

**Comment by goofy7264** [comment]
I certainly do.  Thanks for going through this work.  Been banging my head against the PlatformIO blank  screen issue and trying to figure out the best way to enable my BLtouch for my newly minted SKR Mini E3 1.2.  You've done all the work.  I'm going to give your bin a try tonight hopefully.
