### ISSUE TITLE
[Question] does the bltouch config use z_enstop_min pins or other pins?

### ISSUE THREAD

**Issue by goofy7264** [damvcoool/Marlin-2.0.x-SKR-Mini-E3-v1.2#2]
Does the compiled bin used z_endstop_min pin or another one?  I have my bltouch plugged into the normal z_endstop pins on the Skr Mini e3 and when I attempt to home, the probe does not deploy and the nozzle hits the bed right in the x0,y0 corner.  Also, did you define safe homing?

**Comment by damvcoool** [comment]
I Plug the BLTouch on PC14, the dedicated probe pin.
No, i did not enable Safe Homing (mostly because i don't like it going to the middle of the bed to home Z
This way you get to keep both the Z-Endstop and also use the BLTouch as a Probe.
Also, i just realized i did not enable the screen to configure the offsets, I will update this later

**Comment by goofy7264** [comment]
cool, I'd recommend you put in that you used PC14 as I suspect many will assume to use z_endstop_min

**Comment by damvcoool** [comment]
yeap, i change the wording on my Readme, I will update the image later

**Comment by damvcoool** [comment]
After a little bit of digging i found that the is no graphical option to set the X and Y offset for the probe, the only way to set this offset aside from compiling the code is to use M851. 

Documentation here:
http://marlinfw.org/docs/gcode/M851.html

**Comment by damvcoool** [comment]
@goofy7264 Did the BLTouch worked when connected to the PC14 pin?

**Comment by goofy7264** [comment]
I'm hoping to test it today.  I have set the offsets for my mount via the m851 but havent had the chance to switch the wiring.  I'll let you know.

**Comment by goofy7264** [comment]
Hi, I have tested it and it does now probe correctly.  The issue now is that the motors are getting extremely hot.  Are you experiencing the same thing?

**Comment by damvcoool** [comment]
Nope... Or at least I have not noticed that... I will check on my next print

**Comment by damvcoool** [comment]
How long does it take for the stepper motors to get hot?

**Comment by damvcoool** [comment]
Yes, mine get warm... But not enough to damage the motor... I would say about 40 to 50c
I mean I can keep my finger on the motors and not be uncomfortable... What speed are you printing at?

**Comment by goofy7264** [comment]
I was trying to print at 100% but the motors were getting really hot, couldn't touch them for more than a second.

**Comment by damvcoool** [comment]
Maybe that's the difference? I am printing at 60mm/s with travels up to 100mm/s

**Comment by damvcoool** [comment]
Do you have damperners?

**Comment by goofy7264** [comment]
no, no dampeners.  I I believe I'm set for 50mm/s and 100mm/s in my slicer (cura)

**Comment by damvcoool** [comment]
is it all the motors? EXYZ or only some?
I am trying to research this but since it's not happening with my printer I will be asking a few more questions as i find more data.

**Comment by goofy7264** [comment]
it seems to be all motors.  Z, E and Y for sure.  Will try it again tomorrow.  I saw another thread that said that it may be due to the SPREAD jumper on spread and +5v and it was fixed when moved to the Spread and Ground, but mine is already on Spread and Ground.
