### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by jagr200** [damvcoool/Marlin-2.0.x-SKR-Mini-E3-v1.2#3]
Ok. So I did the firmware with the Bltouch. But using the Z offset switch doesnt make any sort of sense. Because it doesnt allow the BLtouch to account for negative variations in the bed height. So it cant go below 0.00. How are you getting this to work? I used the 256k firmware

**Comment by damvcoool** [comment]
My default z-offset is -3.4mm.
This is because the probe hits the bed before the nozzle does, it just needs to know how far the nozzle would be.

**Comment by jagr200** [comment]
> My default z-offset is -3.4mm.
> This is because the probe hits the bed before the nozzle does, it just needs to know how far the nozzle would be.

But that doesnt allow for it to go any further than -3.4. If it needs to go down to -3.5 for a part of the print it isnt able to do that because the Z is already against the Z stop. I really don't understand how this could work for you.

**Comment by damvcoool** [comment]
For me the probe z_offset at -3.4 my nozzle is already at 0.12 from the bed.
