### ISSUE TITLE
[Question] Source Code for 512 version

### ISSUE THREAD

**Issue by onkytonk** [damvcoool/Marlin-2.0.x-SKR-Mini-E3-v1.2#4]
Hi, 
Any chance you can share your source code for the 512kb version please?

**Comment by damvcoool** [comment]
It's the same source that's on my repo the only difference is that I used the STM32F103RC_bigtree_512K default env to compile it.

**Comment by onkytonk** [comment]
Ah cool. And if I use that as the default env, does it have the eeprom fixes already?
EDIT: Or does it just use the same pins_BTT_SKR_MINI_E3_V1_2.h ?

**Comment by damvcoool** [comment]
It sure what fixes you mean. If you mean moving to 2048 from 1024, then yes, if not then likely those fixes are not yet applied on my repository.
It uses the same as pins_BTT_SKR_MINI_E3_V1_2.h for both 256 and 512
