### ISSUE TITLE
//#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN

### ISSUE THREAD

**Issue by Atorcha** [damvcoool/Marlin-2.0.x-SKR-Mini-E3-v1.2#6]
Why you don't enable //#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN ??

I think you should.

Regards.

**Comment by damvcoool** [comment]
That's because i am not using the BLTouch as a Z-Endstop.
i kept the configuration as intended by BTT where Z has it's own endstop and BL uses it's dedicated pin ;)

**Comment by Atorcha** [comment]
Español???

**Comment by damvcoool** [comment]
La razón por la que no uso los Pines del "parador"-Z es por que estoy siguiendo la guia de BTT (BigTreeTech) donde aconsejan usar el "Parador" que es dedicado para el BLTouch.

Las imagenes de como se acomodan los cables están en el ReadMe.md de este repositorio.

adicionalmente puedes cambiar la configuración, de hecho es lo mejor que podrías hacer para asegurarte que el software funcione mejor con tu impresora 3D.

(sorry for the bad Spanish, it's been a few years)

**Comment by Atorcha** [comment]
OK gracias.
Particularmente, lo he puesto en el Z-Stop, porque, así lo puse en la anterior impresora. En realidad no entiendo porque el fabricante indica que es mejor.

Por otro lado, la imagen del readme no se ve.

![image](https://user-images.githubusercontent.com/4932853/79632055-2de2c780-815d-11ea-8289-54add994b778.png)

**Comment by damvcoool** [comment]
muchas gracias, no había notado que la imagen no esta a la vista.

ya arregle la imagen ;)
