### ISSUE TITLE
STM32F103RC_btt_512K

### ISSUE THREAD

**Issue by Atorcha** [damvcoool/Marlin-2.0.x-SKR-Mini-E3-v1.2#7]
Hello.

Is not better use STM32F103RC_btt_512K instead STM32F103RC_btt for SKR Mini E3 1.2 in Marlin 2.0.5.3 ??

Thanks

**Comment by damvcoool** [comment]
Not quite, not all the boards support 512k, mine for example does not work if i use 512.
I left the configuration the way it is for Maximum compatibility.

also since the size of the bin after compilation is less than 216 there is no need for 512 ;)
